name: Build Images

#on:
#  push:
#    branches:
#      - "master"

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: GHCR Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
#      -
#        # Add support for more platforms with QEMU (optional)
#        # https://github.com/docker/setup-qemu-action
#        name: Set up QEMU
#        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build Klipper
        uses: docker/build-push-action@v6
        with:
          context: .
          cache-to: type=gha
          cache-from: type=gha
          push: true
          tags: ghcr.io/nelsongraca/kdock-klipper:latest
          target: klipper
      -
        name: Build Moonraker
        uses: docker/build-push-action@v6
        with:
          context: .
          cache-to: type=gha
          cache-from: type=gha
          push: true
          tags: ghcr.io/nelsongraca/kdock-moonraker:latest
          target: moonraker
