name: Build Images

#on:
#  push:
#    branches:
#      - "master"

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * *'

jobs:
  base-build:
    name: Build and cache Base
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: GHCR Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.platform }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build Base Cache
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.platform }}
          context: .
          cache-from: type=registry,ref=ghcr.io/nelsongraca/kdock-cache:kdock-${{ env.PLATFORM_PAIR }}
          cache-to: type=registry,ref=ghcr.io/nelsongraca/kdock-cache:kdock-${{ env.PLATFORM_PAIR }},mode=max
          push: false
          provenance: false
          target: kdock
  
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    needs: base-build
    
    strategy:
      fail-fast: false
      matrix:
        component:
          - klipper
          - moonraker
        platform:
          - linux/amd64
          - linux/arm64
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV          
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: GHCR Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.platform }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build ${{matrix.component}}
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.platform }}
          context: .
          cache-from: |
            type=registry,ref=ghcr.io/nelsongraca/kdock-cache:kdock-${{ env.PLATFORM_PAIR }}
            type=registry,ref=ghcr.io/nelsongraca/kdock-cache:${{matrix.component}}-${{ env.PLATFORM_PAIR }}
          cache-to: type=registry,ref=ghcr.io/nelsongraca/kdock-cache:${{matrix.component}}-${{ env.PLATFORM_PAIR }},mode=max
          outputs: type=image,name=ghcr.io/nelsongraca/kdock-${{matrix.component}},push-by-digest=true,name-canonical=true,push=true
          provenance: false
          target: ${{matrix.component}}
      - 
        name: Export digest
        run: |
          mkdir -p /tmp/digests/${{matrix.component}}
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${{matrix.component}}/${digest#sha256:}"          

      - 
        name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ matrix.component }}-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/${{matrix.component}}/*
          if-no-files-found: error
          retention-days: 1
          
  tag:
    name: Tag
    runs-on: ubuntu-latest
    needs:
      - build
    
    strategy:
      fail-fast: false
      matrix:
        component:
          - klipper
          - moonraker
          
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: GHCR Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      -
        name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests/${{ matrix.component }}
          pattern: digests-${{ matrix.component }}-*
          merge-multiple: true
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Create manifest list and push
        working-directory: /tmp/digests/${{matrix.component}}
        run: |
          echo docker buildx imagetools create -t ghcr.io/nelsongraca/kdock-${{matrix.component}}:latest $(printf 'ghcr.io/nelsongraca/kdock-${{matrix.component}}@sha256:%s ' *)          
          docker buildx imagetools create -t ghcr.io/nelsongraca/kdock-${{matrix.component}}:latest $(printf 'ghcr.io/nelsongraca/kdock-${{matrix.component}}@sha256:%s ' *)
  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    needs:
      - base-build
      - build
      - tag
    strategy:
      fail-fast: false
      matrix:
        image:
          - kdock-klipper
          - kdock-moonraker
          - kdock-cache
          
    permissions:
      packages: write
    steps:
      - 
        name: Cleanup
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          dry-run: false
          token: ${{ secrets.GITHUB_TOKEN }}
          package: ${{ matrix.image }}
          delete-untagged: true
